### ISSUE TITLE
Document all the supported directives

### ISSUE THREAD

**Issue by dandv** [bahaaldine/angular-social-count#2]
The usage mentions only `<ng-fb-(like|share|comment)`-count>. What other social networks are supported?

**Comment by ttbarnes** [comment]
:+1: All supported networks should be listed. My understanding of this codebase so far is that it's purely for facebook. If this is the only network supported the repo should be renamed to 'angular-facebook-count' or something like that.

**Comment by bahaaldine** [comment]
added documentation & support for Facebook, Twitter, Pinterest, Linkedin.

Cheers !
