### ISSUE TITLE
Unable to see or run an example

### ISSUE THREAD

**Issue by ttbarnes** [bahaaldine/angular-social-count#3]
You should be able to see an example of the counters without having to install and run the code locally.

Currently, you are unable to run the code locally due to bower/npm/grunt dependancy issues. 

Therefore, I cannot actually see an example in action.

**Comment by bahaaldine** [comment]
I've added a demo site in which one can pass an URL and see the related shared metrics for the respective social networks.

**Comment by ttbarnes** [comment]
NIce one @bahaaldine
